# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  data_download:
    desc: download source data
    dir: data
    cmds:
      - wget https://e.17500.cn/getData/ssq.TXT -O raw_data.txt
  mod:
    desc: download python dep require
    cmds:
      - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
  train:
    desc: train model
    cmds:
      - python src/train_blue_ball.py
  clean:
    cmds:
      - rm -rf ./output/*
